// Angular/src/app/features/task-detail/task-detail-page.component.ts
import { Component, inject } from '@angular/core';
import { toSignal } from '@angular/core/rxjs-interop';
import { ActivatedRoute } from '@angular/router';
import { map } from 'rxjs';

@Component({
  selector: 'app-task-detail-page',
  standalone: true,
  templateUrl: './task-detail-page.component.html',
  styleUrl: './task-detail-page.component.scss',
})
export class TaskDetailPageComponent {
  private readonly route = inject(ActivatedRoute);

  /** Route param <code>id</code> for when you wire the editor + reminders UI. */
  readonly taskId = toSignal(this.route.paramMap.pipe(map((p) => p.get('id'))), { initialValue: null });
}

<section class="panel">
  <h2>Task detail</h2>
  <p class="lead">
    Skeleton for <code>GET /tasks/:id</code>, <code>PATCH /tasks/:id</code>, and reminders under
    <code>/tasks/:taskId/reminders</code>.
  </p>
  <p class="muted">Current route param <code>id</code>: <strong>{{ taskId() || '—' }}</strong></p>
</section>

// React/src/features/task-detail/TaskDetailPage.tsx
import { useParams } from 'react-router-dom';
import '../panel.css';

export function TaskDetailPage() {
  const { id } = useParams();

  return (
    <section className="panel">
      <h2>Task detail</h2>
      <p className="lead">
        Skeleton for <code>GET /tasks/:id</code>, <code>PATCH /tasks/:id</code>, and reminders under{' '}
        <code>/tasks/:taskId/reminders</code>.
      </p>
      <p className="muted">
        Current route param <code>id</code>: <strong>{id ?? '—'}</strong>
      </p>
    </section>
  );
}
