// Angular/src/app/features/shell/app-shell.component.ts
import { CommonModule } from '@angular/common';
import { Component, inject } from '@angular/core';
import { Router, RouterLink, RouterLinkActive, RouterOutlet } from '@angular/router';
import { AuthService } from '../../core/auth/auth.service';

@Component({
  selector: 'app-shell',
  standalone: true,
  imports: [CommonModule, RouterOutlet, RouterLink, RouterLinkActive],
  templateUrl: './app-shell.component.html',
  styleUrl: './app-shell.component.scss',
})
export class AppShellComponent {
  private readonly auth = inject(AuthService);
  private readonly router = inject(Router);

  logout(): void {
    this.auth.logout().subscribe(() => {
      void this.router.navigateByUrl('/login');
    });
  }
}

<div class="shell">
  <header class="topbar">
    <div class="brand">Tasks &amp; Reminders</div>
    <nav>
      <a routerLink="/tasks" routerLinkActive="active" [routerLinkActiveOptions]="{ exact: true }">Tasks</a>
      <a routerLink="/lists" routerLinkActive="active">Lists</a>
      <a routerLink="/profile" routerLinkActive="active">Profile</a>
    </nav>
    <button type="button" class="ghost" (click)="logout()">Log out</button>
  </header>

  <main class="content">
    <router-outlet />
  </main>
</div>

// React/src/features/shell/AppShell.tsx
import { NavLink, Outlet, useNavigate } from 'react-router-dom';
import { logout } from '../../core/auth/auth';
import './AppShell.css';

export function AppShell() {
  const navigate = useNavigate();

  function onLogout(): void {
    void logout().then(() => {
      void navigate('/login', { replace: true });
    });
  }

  return (
    <div className="shell">
      <header className="topbar">
        <div className="brand">Tasks &amp; Reminders</div>
        <nav>
          <NavLink to="/tasks" end className={({ isActive }) => (isActive ? 'active' : '')}>
            Tasks
          </NavLink>
          <NavLink to="/lists" className={({ isActive }) => (isActive ? 'active' : '')}>
            Lists
          </NavLink>
          <NavLink to="/profile" className={({ isActive }) => (isActive ? 'active' : '')}>
            Profile
          </NavLink>
        </nav>
        <button type="button" className="ghost" onClick={onLogout}>
          Log out
        </button>
      </header>

      <main className="content">
        <Outlet />
      </main>
    </div>
  );
}
