// Angular/src/app/features/lists/lists-page.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-lists-page',
  standalone: true,
  templateUrl: './lists-page.component.html',
  styleUrl: './lists-page.component.scss',
})
export class ListsPageComponent {}

<section class="panel">
  <h2>Task lists</h2>
  <p class="lead">
    Skeleton for <code>GET /lists</code>, <code>POST /lists</code>, <code>PATCH /lists/:id</code>,
    <code>DELETE /lists/:id</code>, and <code>GET /lists/:id/tasks</code>.
  </p>
</section>

// React/src/features/lists/ListsPage.tsx
import '../panel.css';

export function ListsPage() {
  return (
    <section className="panel">
      <h2>Task lists</h2>
      <p className="lead">
        Skeleton for <code>GET /lists</code>, <code>POST /lists</code>, <code>PATCH /lists/:id</code>,{' '}
        <code>DELETE /lists/:id</code>, and <code>GET /lists/:id/tasks</code>.
      </p>
    </section>
  );
}
