// React/src/features/tasks/TasksPage.tsx
import '../panel.css';

export function TasksPage() {
  return (
    <section className="panel">
      <h2>Tasks</h2>
      <p className="lead">
        Skeleton route. Next steps: call <code>getTasks()</code> from <code>tasks-reminders-api</code> with query params
        (<code>status</code>, <code>due_before</code>, <code>list_id</code>, <code>priority</code>), render a list, and use{' '}
        <code>PATCH /tasks/:id/complete</code> for the checkbox toggle.
      </p>
      <p className="muted">Deep link example (after you build the table): <code>/tasks/42</code> for detail + reminders.</p>
    </section>
  );
}

// Angular/src/app/features/tasks/tasks-page.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-tasks-page',
  standalone: true,
  templateUrl: './tasks-page.component.html',
  styleUrl: './tasks-page.component.scss',
})
export class TasksPageComponent {}

<section class="panel">
  <h2>Tasks</h2>
  <p class="lead">
    Skeleton route. Next steps: call <code>TasksRemindersApiService.getTasks()</code> with query params
    (<code>status</code>, <code>due_before</code>, <code>list_id</code>, <code>priority</code>), render a list, and use
    <code>PATCH /tasks/:id/complete</code> for the checkbox toggle.
  </p>
  <p class="muted">Deep link example (after you build the table): <code>/tasks/42</code> for detail + reminders.</p>
</section>
